name: Compile Latex and Release PDF  

on:
  push:
    branches:    
      - main
    tags:
      - '*.*.*-1'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: routine.tex
 
      - name: Commit files
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          git config --local user.name "gh-actionsBot"
          git config --local user.email "actions@github.com"
          git add *
          git commit -am "auto-deploy pdf"
          git push origin main -f
        env:
          REPO_KEY: ${{secrets.SECRET}}
          username: gh-actionsBot
